options:
  port:
    type: int
    default: 80
    description: "Port to be used from the web server"
  default-user:
    type: string
    default: admin
    description: "Name of default FreshRSS user"
  language:
    type: string
    default: en
    description: "Language for FreshRSS installation"
  auth-type:
    type: string
    default: none
    description: "Can be: 'form', 'http_auth' (using the Web server access control), 'none' (dangerous)"
  db-user:
    type: string
    default: "freshrss"
    description: "Name for the FreshRSS user in the database"
  db-prefix:
    type: string
    default: "freshrss"
    description: "An optional prefix in front of the names of the tables"
  environment:
    type: string
    default: debug
  base-url:
    type: string
    default: 'rss.pdl'
    description: "Should be a public (routable) URL if possible, and is used for push (WebSub), for some API functions (e.g. favicons), and external URLs in FreshRSS."
