#!/usr/local/sbin/charm-env python3

from charmhelpers.core.hookenv import (
    action_get
)

from charms.layer.fresh_rss import run_script

if __name__ == '__main__':
    opts = []

    for arg, value in action_get().items():
        opts.extend(['--' + arg.replace('_', '-'), value])

    run_script('create-user', opts)
